services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: strongPassword
      MYSQL_DATABASE: testtrack
      MYSQL_USER: app_user
      MYSQL_PASSWORD: strongPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pstrongPassword --silent"]
      interval: 5s
      timeout: 3s
      retries: 20


volumes:
  mysql_data: