# backend/Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Instala dependências
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Garanta que o Nest escute em 0.0.0.0
# (no main.ts: app.listen(3000, '0.0.0.0'))
EXPOSE 3000

CMD ["npm", "run", "start:dev"]
