export enum TipoTeste {
  FUNCTIONAL = 'FUNCIONAL',
  REGRESSION = 'REGRESSAO',
  PERFORMANCE = 'DESEMPENHO',
  SECURITY = 'SEGURANCA',
  USABILITY = 'USABILIDADE',
  INTEGRATION = 'INTEGRACAO',
  ACCEPTANCE = 'ACEITACAO',
  AUTOMATIZED = 'AUTOMATIZADO',
  MANUAL = 'MANUAL',
}

export enum Prioridade {
  LOW = 'BAIXA',
  MEDIUM = 'MEDIA',
  HIGH = 'ALTA',
  CRITICAL = 'CRITICA',
}

export enum StatusCasoTeste {
  PENDING = 'PENDENTE',
  IN_PROGRESS = 'EM_ANDAMENTO',
  APPROVED = 'APROVADO',
  REPROVED = 'REPROVADO',
  BLOCKED = 'BLOQUEADO',
  CANCELED = 'CANCELADO',
}