export enum TestType {
  FUNCIONAL = 'FUNCIONAL',
  REGRESSAO = 'REGRESSAO',
  PERFORMANCE = 'DESEMPENHO',
  SECURITY = 'SEGURANCA',
  USABILITY = 'USABILIDADE',
  INTEGRATION = 'INTEGRACAO',
  ACCEPTANCE = 'ACEITACAO',
  AUTOMATIZED = 'AUTOMATIZADO',
  MANUAL = 'MANUAL',
}

export enum Priority {
  NONE = 'NENHUM',
  LOW = 'BAIXA',
  MEDIUM = 'MEDIA',
  HIGH = 'ALTA',
  CRITICAL = 'CRITICA',
}

export enum TestCaseStatus {
  NOT_STARTED = 'NAO_INICIADO',
  PENDING = 'PENDENTE',
  IN_PROGRESS = 'EM_ANDAMENTO',
  APPROVED = 'APROVADO',
  REPROVED = 'REPROVADO',
  BLOCKED = 'BLOQUEADO',
  CANCELED = 'CANCELADO',
  FINISHED = 'CONCLUIDO',
}

export enum FunctionalTestFramework {
  SELENIUM = 'SELENIUM',
  CYPRESS = 'CYPRESS',
  ROBOT_FRAMEWORK = 'ROBOT_FRAMEWORK',
}

export enum BugStatus {
  OPEN = 'ABERTO',
  IN_PROGRESS = 'EM_ANDAMENTO',
  FIXED = 'CORRIGIDO',
  CLOSED = 'FECHADO',
  REOPENED = 'REABERTO',
}
